# Generated by Django 5.2.16 on 2026-07-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverification_passwordreset_revokedtoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='code',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='RevokedToken',
        ),
    ]
