# Generated by Django 6.0.6 on 2026-07-21 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('content_ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentgeneration',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations', to='brands.brand'),
        ),
    ]
