version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=syncflow_db
      - POSTGRES_USER=syncflow_user
      - POSTGRES_PASSWORD=syncflow_pass
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://syncflow_user:syncflow_pass@db:5432/syncflow_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DEBUG=True
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A syncfloww worker -l info
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://syncflow_user:syncflow_pass@db:5432/syncflow_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DEBUG=True
    depends_on:
      - db
      - redis
      - web

  celery-beat:
    build: .
    command: celery -A syncfloww beat -l info
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://syncflow_user:syncflow_pass@db:5432/syncflow_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DEBUG=True
    depends_on:
      - db
      - redis
      - celery

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery

volumes:
  postgres_data:
