# Generated by Django 6.0.6 on 2026-07-14 13:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('target_audience', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('primary_color', models.CharField(blank=True, max_length=7)),
                ('secondary_color', models.CharField(blank=True, max_length=7)),
                ('logo', models.ImageField(blank=True, upload_to='logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BrandAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('file', models.FileField(upload_to='brand-assets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='brands.brand')),
            ],
        ),
        migrations.CreateModel(
            name='BrandGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('content', models.TextField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidelines', to='brands.brand')),
            ],
        ),
        migrations.CreateModel(
            name='BrandVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tone', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('do_list', models.JSONField(blank=True, default=list)),
                ('dont_list', models.JSONField(blank=True, default=list)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice', to='brands.brand')),
            ],
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='unique_workspace_brand_name'),
        ),
    ]
