# Generated by Django 6.0.6 on 2026-07-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='entity_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='entity_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
