# Generated by Django 5.2.16 on 2026-07-15 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('meeting_type', models.CharField(choices=[('weekly', 'Weekly Operations Sync'), ('monthly', 'Monthly Strategic Alignment'), ('emergency', 'Ad-hoc Emergency Review')], default='weekly', max_length=50)),
                ('transcript', models.TextField()),
                ('summary', models.TextField()),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_meetings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
