# Generated by Django 5.2.16 on 2026-08-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('publisher', models.CharField(default='SyncflowAI', max_length=255)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromptPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(default='Social Media', max_length=100)),
                ('prompts_count', models.IntegerField(default=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_installed', models.BooleanField(default=False)),
            ],
        ),
    ]
