# Generated by Django 6.0.6 on 2026-07-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content_brand_content_content_type_and_more'),
        ('publishing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_assets',
            field=models.ManyToManyField(blank=True, related_name='posts', to='content.mediaasset'),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
    ]
