# Generated by Django 5.2.16 on 2026-07-25 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_brandasset_brandguideline_brandvoice_oauthtoken_and_more'),
        ('workspaces', '0002_workspace_created_by_workspace_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_brands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brand',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='brand',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='brand',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='workspaces.workspace'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('workspace', 'slug')},
        ),
        migrations.CreateModel(
            name='BrandKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('knowledge_type', models.CharField(choices=[('ABOUT', 'About'), ('PRODUCT', 'Product'), ('SERVICE', 'Service'), ('FAQ', 'FAQ'), ('POLICY', 'Policy'), ('AUDIENCE', 'Audience'), ('CAMPAIGN', 'Campaign'), ('GUIDELINE', 'Guideline'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_items', to='social.brand')),
            ],
        ),
        migrations.CreateModel(
            name='BrandProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(blank=True, default='', max_length=255)),
                ('mission', models.TextField(blank=True, default='')),
                ('vision', models.TextField(blank=True, default='')),
                ('industry', models.CharField(blank=True, default='', max_length=255)),
                ('target_audience', models.TextField(blank=True, default='')),
                ('brand_voice', models.CharField(blank=True, default='', max_length=255)),
                ('tone', models.CharField(blank=True, default='', max_length=255)),
                ('language', models.CharField(default='en', max_length=50)),
                ('values', models.JSONField(blank=True, default=list)),
                ('products_services', models.JSONField(blank=True, default=list)),
                ('unique_selling_points', models.JSONField(blank=True, default=list)),
                ('do_not_say', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='social.brand')),
            ],
        ),
    ]
