# Generated by Django 5.2.16 on 2026-07-27 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_remove_brand_user_socialaccount_account_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialaccount',
            options={'ordering': ['-created_at']},
        ),
    ]
