# Generated by Django 6.0.7 on 2026-08-14 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_alter_socialaccount_options'),
        ('workspaces', '0002_workspace_created_by_workspace_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='oauthtoken',
            old_name='refresh_token',
            new_name='encrypted_refresh_token',
        ),
        migrations.RemoveField(
            model_name='oauthtoken',
            name='access_token',
        ),
        migrations.AddField(
            model_name='oauthtoken',
            name='encrypted_access_token',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='oauthtoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='capabilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='granted_scopes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Consent'), ('ACTIVE', 'Active'), ('EXPIRED', 'Token Expired'), ('REAUTH_REQUIRED', 'Re-authentication Required'), ('REVOKED', 'Access Revoked'), ('ERROR', 'Connection Error'), ('DISCONNECTED', 'Disconnected')], default='ACTIVE', max_length=30),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='OAuthAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('OAUTH_INITIATED', 'OAuth Session Initiated'), ('OAUTH_SUCCESS', 'OAuth Connection Successful'), ('OAUTH_FAILED', 'OAuth Authorization Failed'), ('TOKEN_REFRESHED', 'Token Refreshed'), ('VERIFIED', 'Connection Verified'), ('DISCONNECTED', 'Account Disconnected'), ('REVOKED', 'Token Revoked')], max_length=50)),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_audit_logs', to='social.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_audit_logs', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
