# Generated by Django 6.1.1 on 2026-10-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_rename_refresh_token_oauthtoken_encrypted_refresh_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='onboarding_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
