# Generated by Django 5.2.16 on 2026-07-27 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('social', '0006_alter_socialaccount_options'),
        ('workspaces', '0002_workspace_created_by_workspace_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='social.brand'),
        ),
        migrations.AddField(
            model_name='content',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='workspaces.workspace'),
        ),
    ]
