# Generated by Django 6.0.7 on 2026-08-14 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('social', '0006_alter_socialaccount_options'),
        ('workspaces', '0002_workspace_created_by_workspace_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_items', to='social.brand'),
        ),
        migrations.AddField(
            model_name='media',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='workspaces.workspace'),
        ),
    ]
