# Generated by Django 6.0.3 on 2026-03-09 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=50)),
                ('parameters', models.JSONField(default=dict)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.agent')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trigger_condition', models.JSONField(default=dict)),
                ('action', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='core.agenttask')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=50)),
                ('account_id', models.CharField(max_length=100)),
                ('access_token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='core.brand')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='social_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='core.socialaccount'),
        ),
        migrations.AddIndex(
            model_name='agenttask',
            index=models.Index(fields=['agent'], name='core_agentt_agent_i_6ed908_idx'),
        ),
        migrations.AddIndex(
            model_name='agenttask',
            index=models.Index(fields=['status'], name='core_agentt_status_1e13de_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['agent_task'], name='core_automa_agent_t_0f53d8_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['owner'], name='core_brand_owner_i_9eb322_idx'),
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['brand'], name='core_social_brand_i_56bfae_idx'),
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['platform_name', 'account_id'], name='core_social_platfor_3d1aad_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['social_account'], name='core_agent_social__ca0ec5_idx'),
        ),
    ]
